#include "ecs/_zg_ecs_.h"


int ZG_IDX_EC_TRANSFORM=ZG_IDX_EC_INVALID;
int ZG_IDX_EC_GEOMETRY=ZG_IDX_EC_INVALID;
int ZG_IDX_EC_MATERIAL=ZG_IDX_EC_INVALID;
int ZG_IDX_EC_TEXTURE=ZG_IDX_EC_INVALID;
int ZG_IDX_EC_SPRITE_RENDERER=ZG_IDX_EC_INVALID;
int ZG_IDX_EC_TEXTBOX_RENDERER=ZG_IDX_EC_INVALID;
int ZG_IDX_EC_TRANSFORM_ANIMATION=ZG_IDX_EC_INVALID;
int ZG_IDX_EC_MATERIAL_ANIMATION=ZG_IDX_EC_INVALID;
int ZG_IDX_EC_COLLISION_DATA=ZG_IDX_EC_INVALID;
