#include "zg_gui.h"


typedef struct{
	MapString 			* 	windows;	// it saves its layers
	TextureManager   	*   texture_manager;
}GUIWindowManagerData;

void GUIWindowManager_OnDeleteGUIWindow(MapStringNode *node){
	GUIWindow *wnd=(GUIWindow *)node->val;

	if(wnd != NULL){
		GUIWindow_Delete(wnd);
	}
}

void GUIWindowManager_OnDeleteTexture(MapStringNode *node){
	Texture *texture=(Texture *)node->val;

	if(texture != NULL){
		Texture_Delete(texture);
	}
}

// MEMBERS
GUIWindowManager *GUIWindowManager_New(TextureManager	* _texture_manager){
	GUIWindowManager *tmm=NEW(GUIWindowManager);
	GUIWindowManagerData *data=NEW(GUIWindowManagerData);

	data->windows = MapString_New();//new std::map<std::string,TTFont *>();
	data->texture_manager = _texture_manager;

	data->windows->on_delete=GUIWindowManager_OnDeleteGUIWindow;

	tmm->data=data;

	return tmm;
}

bool GUIWindowManager_LoadFromMemory(
		GUIWindowManager *_this
		,const char *_path
		,uint8_t *_xml_buf
		,size_t _xml_len
	){

	char filename[MAX_PATH]={0};
	bool ok=false;
	XMLDoc doc;
	XMLDoc_init(&doc);

	Texture *texture;
	GUIWindowManagerData *data=_this->data;

	// first read tilesets...
	XMLDoc_parse_buffer_DOM(_xml_buf, C2SX(_path),&doc);

	XMLDoc_print(&doc, stdout, C2SX("\n"), C2SX("\t"), false, 0, 4);

	XMLDoc_free(&doc);


	return ok;

}

/**
 * Load a set of GUIWindow from exported files from Aseprite
 * @_this: GUIWindowManager object
 * @_texture_filename: Texture filename (it can be .png,jpg,etc)
 * @_json_filename: Json file generated by Aseprite
 * @_extra_json_filename: Json file where it adds some extra information per frame (for instance collider)
 */
bool GUIWindowManager_Load(GUIWindowManager *_this,const char *_json_tmx_file){

	BufferByte *_xml_buf=NULL;bool ok=false;
	char *_path=NULL;


	if((_xml_buf=File_Read(_json_tmx_file))!=NULL){
		ok=GUIWindowManager_LoadFromMemory(
				_this
				,_path=Path_GetDirectoryName(_json_tmx_file)
				,_xml_buf->ptr
				,_xml_buf->len
		);
	}


	if(_xml_buf) BufferByte_Delete(_xml_buf);
	if(_path) free(_path);


	return ok;
}

GUIWindow *GUIWindowManager_Get(GUIWindowManager *_this, const char *key){
	GUIWindowManagerData *data=_this->data;

	return MapString_GetValue(data->windows,key,NULL);
}



void  GUIWindowManager_Delete(GUIWindowManager *_this){
	GUIWindowManagerData 	*data=_this->data;

	MapString_Delete(data->windows);
	//MapString_Delete(data->textures);

	FREE(data);
	FREE(_this);
}
