#include "ZG_Luts.c"
#include "ZG_Vector2i.c"
#include "ZG_Vector2f.c"
#include "ZG_Vector3i.c"
#include "ZG_Vector3f.c"
#include "ZG_Vector4f.c"
#include "ZG_Matrix3f.c"
#include "ZG_Matrix4f.c"

#include "ZG_Quaternion.c"
#include "ZG_Rectangle4f.c"
#include "ZG_Rectangle4i.c"
#include "ZG_BoundingBox.c"
