#include "Luts.c"
#include "Vector2i.c"
#include "Vector2f.c"
#include "Vector3i.c"
#include "Vector3f.c"
#include "Vector4f.c"
#include "Matrix3f.c"
#include "Matrix4f.c"

#include "Quaternion.c"
#include "Rectanglef.c"
#include "Rectanglei.c"
