
// gldebug must be the first one....

#include "ZG_BufferByte.c"
#include "ZG_BufferFloat.c"
#include "ZG_BufferShort.c"
#include "gl/glextra.c"
#include "jpeg/jpeg_mem.c"
#include "3rdparty/cXML/cXML.c"
#include "3rdparty/cJSON/cJSON.c"
#include "3rdparty/gifdec/gifdec.c"
#include "3rdparty/lodepng/lodepng.c"

#include "ZG_Directory.c"
#include "ZG_File.c"

#include "ZG_List.c"
#include "ZG_Log.c"
#include "ZG_MapInt.c"
#include "ZG_MapString.c"
#include "ZG_MapStringIterator.c"
#include "ZG_Path.c"
#include "sdl/_zg_base_sdl_.c"
//#include "sdl/SDL_windows_main.c"
#include "ZG_Term.c"
#include "util-fmemopen.c"
#include "ZG_Bit.c"
#include "ZG_FileSystem.c"
#include "ZG_Guid.c"
#include "ZG_String.c"
#include "zg_memory.c"
