
// gldebug must be the first one....

#include "BufferByte.c"
#include "BufferFloat.c"
#include "BufferShort.c"
#include "gl/glextra.c"
#include "jpeg/jpeg.c"
#include "3rdparty/xml.c/src/xml.c"
#include "3rdparty/cJSON/cJSON.c"
#include "3rdparty/gifdec/gifdec.c"
#include "3rdparty/lodepng/lodepng.c"

#include "Directory.c"
#include "File.c"

#include "List.c"
#include "Log.c"
#include "MapInt.c"
#include "MapString.c"
#include "MapStringIterator.c"
#include "Path.c"
#include "sdl/zg_sdl.c"
//#include "sdl/SDL_windows_main.c"
#include "Term.c"
#include "util-fmemopen.c"
#include "Bit.c"
#include "FileSystem.c"
#include "Guid.c"
#include "StrUtils.c"
#include "zg_memory.c"
